{{- range .Values.certificates }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  isCA: true
  duration: 87600h # 10 years
  secretName: {{ .name }}
  commonName: {{ .commonName }}
  privateKey:
    algorithm: ECDSA
    size: 256
  subject:
    organizations:
    - cluster.local
    - cert-manager
  dnsNames: {{ .dnsNames | toYaml | nindent 4 }}
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  secretName: {{ .name }}
{{- end }}
