clubs:
  - name: xquare
    users:
    - "rlaisqls"
    - "alsdl0629"
    - "alsco39"
    - "tedsoftj1123"
    - "jyk1029"
    projects:
    - application
    - attachment 
    - dormitory-admin
    - point
    - meal       
    - school-meal
    - report     
    - schedule   
    - timetable-be
    - feed 
    - git        
    - notification-be 
  - name: pick
    users:
    - "rlaisqls"
    - "alsdl0629"
    - "alsco39"
    - "tedsoftj1123"
    - "jyk1029"
    projects:
    - pick-admin     
    - pick        
    - pick-teacher   
  - name: repo
    users:
    - "rlaisqls"
    projects:
    - repo
    - repo-admin
    - repo-main
    - repo-user
  - name: mukgen
    users: 
    - HyunSu1768
    projects:
    - mukgen