apiVersion: v2
name: karpenter
description: A Helm chart for Karpenter, an open-source node provisioning project built for Kubernetes.
type: application
version: 1.0.16
appVersion: 0.30.0
dependencies:
- name: karpenter
  version: 0.16.3
  repository: https://charts.karpenter.sh/
