apiVersion: v2
name: karpenter
description: A Helm chart for Karpenter, an open-source node provisioning project built for Kubernetes.
type: application
version: 1.0.52
appVersion: 0.32.7
dependencies:
- name: karpenter
  version: "v0.34.1"
  repository: oci://public.ecr.aws/karpenter