apiVersion: v1
name: cert-manager
# The version and appVersion fields are set automatically by the release tool
version: v1.12.13
appVersion: v1.12.4
kubeVersion: ">= 1.22.0-0"
description: A Helm chart for cert-manager
home: https://github.com/cert-manager/cert-manager
dependencies:
- name: cert-manager
  version: v1.12.4
  repository: https://charts.jetstack.io
